[2025-08-16 22:08:43,235:INFO:main:Welcome to our custom log]
[2025-08-17 22:26:11,890:INFO:main:>>>>>>>>> stage Data Ingestion stage started <<<<<<<<<]
[2025-08-17 22:26:11,891:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-17 22:26:11,892:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-17 22:26:11,892:INFO:common:created directory at: artifacts]
[2025-08-17 22:26:11,893:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-17 22:26:11,893:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-17 22:26:30,190:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-17 22:26:30,461:INFO:main:>>>>>>>>>> stage Data Ingestion stage completed <<<<<<<<<<< 
 
x==============================x]
[2025-08-18 16:39:52,515:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 16:39:52,516:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 16:39:52,517:INFO:common:created directory at: artifacts]
[2025-08-18 16:39:52,518:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 17:11:14,777:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 17:11:14,778:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 17:11:14,779:INFO:common:created directory at: artifacts]
[2025-08-18 17:11:14,779:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 17:11:20,581:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 17:11:20,583:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 17:11:20,583:INFO:common:created directory at: artifacts]
[2025-08-18 17:11:20,584:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 17:15:02,967:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 17:15:02,969:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 17:15:02,969:INFO:common:created directory at: artifacts]
[2025-08-18 17:15:02,970:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 17:16:34,238:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 17:16:34,240:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 17:16:34,240:INFO:common:created directory at: artifacts]
[2025-08-18 17:16:34,241:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 17:18:41,931:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 17:18:41,933:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 17:18:41,933:INFO:common:created directory at: artifacts]
[2025-08-18 17:18:41,934:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 17:18:59,773:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-18 17:18:59,800:WARNING:optimizer:At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 17:18:59,801:WARNING:__init__:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 18:06:28,923:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-18 18:06:28,925:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 18:06:28,925:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 18:06:28,925:INFO:common:created directory at: artifacts]
[2025-08-18 18:06:28,925:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-18 18:06:28,925:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 18:06:47,654:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 18:06:47,926:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-18 18:06:47,926:INFO:main:*******************]
[2025-08-18 18:06:47,926:INFO:main:>>>>>> stage Prepare base model started <<<<<<]
[2025-08-18 18:06:47,927:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 18:06:47,927:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 18:06:47,927:INFO:common:created directory at: artifacts]
[2025-08-18 18:06:47,928:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 18:06:48,075:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-18 18:06:48,103:WARNING:optimizer:At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 18:06:48,104:WARNING:__init__:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 18:06:48,123:INFO:main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-18 19:20:00,883:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:20:00,884:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:20:00,885:INFO:common:created directory at: artifacts]
[2025-08-18 19:20:00,886:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:22:11,604:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:22:11,606:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:22:11,606:INFO:common:created directory at: artifacts]
[2025-08-18 19:22:11,607:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:23:02,094:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:23:02,095:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:23:02,096:INFO:common:created directory at: artifacts]
[2025-08-18 19:23:02,096:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:27:45,429:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:27:45,431:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:27:45,432:INFO:common:created directory at: artifacts]
[2025-08-18 19:27:45,432:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:30:26,860:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:30:26,862:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:30:26,863:INFO:common:created directory at: artifacts]
[2025-08-18 19:30:26,863:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:32:37,412:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:32:37,414:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:32:37,414:INFO:common:created directory at: artifacts]
[2025-08-18 19:32:37,415:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:32:57,000:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:32:57,001:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:32:57,002:INFO:common:created directory at: artifacts]
[2025-08-18 19:32:57,002:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:38:52,445:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:38:52,447:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:38:52,447:INFO:common:created directory at: artifacts]
[2025-08-18 19:38:52,448:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:39:12,375:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:39:12,377:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:39:12,377:INFO:common:created directory at: artifacts]
[2025-08-18 19:39:12,378:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:45:06,200:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:45:06,202:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:45:06,203:INFO:common:created directory at: artifacts]
[2025-08-18 19:45:06,203:INFO:common:created directory at: artifacts/training]
[2025-08-18 19:59:25,963:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 19:59:25,965:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 19:59:25,965:INFO:common:created directory at: artifacts]
[2025-08-18 19:59:25,966:INFO:common:created directory at: artifacts/training]
[2025-08-18 20:55:38,784:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-18 20:55:38,785:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 20:55:38,785:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 20:55:38,786:INFO:common:created directory at: artifacts]
[2025-08-18 20:55:38,786:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-18 20:55:38,786:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 20:55:57,662:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 20:55:57,922:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-18 20:55:57,922:INFO:main:*******************]
[2025-08-18 20:55:57,922:INFO:main:>>>>>> stage Prepare base model started <<<<<<]
[2025-08-18 20:55:57,923:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 20:55:57,923:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 20:55:57,923:INFO:common:created directory at: artifacts]
[2025-08-18 20:55:57,923:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 20:55:58,100:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-18 20:55:58,125:WARNING:optimizer:At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 20:55:58,126:WARNING:__init__:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 20:55:58,145:INFO:main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-18 20:58:37,360:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-18 20:58:37,360:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 20:58:37,361:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 20:58:37,361:INFO:common:created directory at: artifacts]
[2025-08-18 20:58:37,361:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-18 20:58:37,361:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 20:59:10,362:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-18 20:59:10,363:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 20:59:10,364:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 20:59:10,364:INFO:common:created directory at: artifacts]
[2025-08-18 20:59:10,364:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-18 20:59:10,364:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 20:59:29,624:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 20:59:29,883:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-18 20:59:29,883:INFO:main:*******************]
[2025-08-18 20:59:29,883:INFO:main:>>>>>> stage Prepare base model started <<<<<<]
[2025-08-18 20:59:29,884:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 20:59:29,885:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 20:59:29,885:INFO:common:created directory at: artifacts]
[2025-08-18 20:59:29,885:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 20:59:29,885:ERROR:main:"'ConfigBox' object has no attribute 'base_model_path'"]
Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 503, in __getitem__
    return super().__getitem__(item)
KeyError: 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
AttributeError: 'ConfigBox' object has no attribute 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 503, in __getitem__
    return super().__getitem__(item)
KeyError: 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
AttributeError: 'ConfigBox' object has no attribute 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 26, in <module>
    prepare_base_model.main()
  File "/Users/sneha/MLOps/src/cnnClassifier/pipeline/stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "/Users/sneha/MLOps/src/cnnClassifier/config/configuration.py", line 46, in get_prepare_base_model_config
    base_model_path=Path(config.base_model_path),
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'base_model_path'"
[2025-08-18 21:00:39,610:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-18 21:00:39,610:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 21:00:39,611:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 21:00:39,611:INFO:common:created directory at: artifacts]
[2025-08-18 21:00:39,611:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-18 21:00:39,611:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 21:00:59,305:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 21:00:59,567:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-18 21:00:59,567:INFO:main:*******************]
[2025-08-18 21:00:59,567:INFO:main:>>>>>> stage Prepare base model started <<<<<<]
[2025-08-18 21:00:59,568:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 21:00:59,569:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 21:00:59,569:INFO:common:created directory at: artifacts]
[2025-08-18 21:00:59,569:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 21:00:59,569:ERROR:main:"'ConfigBox' object has no attribute 'base_model_path'"]
Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 503, in __getitem__
    return super().__getitem__(item)
KeyError: 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
AttributeError: 'ConfigBox' object has no attribute 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 503, in __getitem__
    return super().__getitem__(item)
KeyError: 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'base_model_path'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
AttributeError: 'ConfigBox' object has no attribute 'base_model_path'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 26, in <module>
    prepare_base_model.main()
  File "/Users/sneha/MLOps/src/cnnClassifier/pipeline/stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
  File "/Users/sneha/MLOps/src/cnnClassifier/config/configuration.py", line 46, in get_prepare_base_model_config
    base_model_path=Path(config.base_model_path),
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/box/box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'base_model_path'"
[2025-08-18 21:10:00,499:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-18 21:10:00,500:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 21:10:00,500:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 21:10:00,500:INFO:common:created directory at: artifacts]
[2025-08-18 21:10:00,500:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-18 21:10:00,500:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 21:10:20,488:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 21:10:20,727:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-18 21:10:20,727:INFO:main:*******************]
[2025-08-18 21:10:20,727:INFO:main:>>>>>> stage Prepare base model started <<<<<<]
[2025-08-18 21:10:20,728:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 21:10:20,728:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 21:10:20,728:INFO:common:created directory at: artifacts]
[2025-08-18 21:10:20,728:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 21:10:20,912:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-18 21:10:20,940:WARNING:optimizer:At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 21:10:20,941:WARNING:__init__:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 21:10:20,962:INFO:main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-18 21:12:23,197:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-18 21:12:23,197:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 21:12:23,198:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 21:12:23,198:INFO:common:created directory at: artifacts]
[2025-08-18 21:12:23,198:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-18 21:12:23,198:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 21:12:42,329:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-18 21:12:42,585:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-18 21:12:42,585:INFO:main:*******************]
[2025-08-18 21:12:42,585:INFO:main:>>>>>> stage Prepare base model started <<<<<<]
[2025-08-18 21:12:42,586:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 21:12:42,586:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 21:12:42,586:INFO:common:created directory at: artifacts]
[2025-08-18 21:12:42,586:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-18 21:12:42,778:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-18 21:12:42,805:WARNING:optimizer:At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 21:12:42,806:WARNING:__init__:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-08-18 21:12:42,825:INFO:main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-18 21:12:42,825:INFO:main:*******************]
[2025-08-18 21:12:42,825:INFO:main:>>>>>> stage Training started <<<<<<]
[2025-08-18 21:12:42,826:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-18 21:12:42,826:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-18 21:12:42,826:INFO:common:created directory at: artifacts]
[2025-08-18 21:12:42,826:INFO:common:created directory at: artifacts/training]
[2025-08-18 21:13:01,081:INFO:main:>>>>>> stage Training completed <<<<<<

x==========x]
[2025-08-19 00:04:38,029:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 00:04:38,032:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 00:04:38,032:INFO:common:created directory at: artifacts]
[2025-08-19 00:04:44,824:INFO:common:json file saved at: scores.json]
[2025-08-19 00:04:46,618:INFO:builder_impl:Assets written to: /var/folders/6h/0lk621m94411dkbcgd43t2vc0000gn/T/tmp8q1an01i/model/data/model/assets]
[2025-08-19 00:16:59,168:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 00:16:59,170:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 00:16:59,171:INFO:common:created directory at: artifacts]
[2025-08-19 00:17:05,798:INFO:common:json file saved at: scores.json]
[2025-08-19 00:17:07,670:INFO:builder_impl:Assets written to: /var/folders/6h/0lk621m94411dkbcgd43t2vc0000gn/T/tmpf7p91oxe/model/data/model/assets]
[2025-08-19 00:19:00,607:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 00:19:00,609:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 00:19:00,610:INFO:common:created directory at: artifacts]
[2025-08-19 00:19:07,460:INFO:common:json file saved at: scores.json]
[2025-08-19 00:19:09,298:INFO:builder_impl:Assets written to: /var/folders/6h/0lk621m94411dkbcgd43t2vc0000gn/T/tmpxx7ne_eo/model/data/model/assets]
[2025-08-19 01:04:43,109:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-19 01:04:43,110:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 01:04:43,111:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 01:04:43,111:INFO:common:created directory at: artifacts]
[2025-08-19 01:04:43,111:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-19 01:04:43,111:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-19 01:05:01,366:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-19 01:05:01,638:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-19 01:05:01,638:INFO:main:*******************]
[2025-08-19 01:05:01,638:INFO:main:>>>>>> stage Prepare base model started <<<<<<]
[2025-08-19 01:05:01,639:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 01:05:01,639:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 01:05:01,639:INFO:common:created directory at: artifacts]
[2025-08-19 01:05:01,640:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-19 01:05:01,799:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-19 01:05:01,826:WARNING:optimizer:At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-08-19 01:05:01,827:WARNING:__init__:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-08-19 01:05:01,848:INFO:main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-19 01:05:01,848:INFO:main:*******************]
[2025-08-19 01:05:01,848:INFO:main:>>>>>> stage Training started <<<<<<]
[2025-08-19 01:05:01,848:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 01:05:01,849:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 01:05:01,849:INFO:common:created directory at: artifacts]
[2025-08-19 01:05:01,849:INFO:common:created directory at: artifacts/training]
[2025-08-19 01:05:22,673:INFO:main:>>>>>> stage Training completed <<<<<<

x==========x]
[2025-08-19 01:05:22,673:INFO:main:*******************]
[2025-08-19 01:05:22,673:INFO:main:>>>>>> stage Evaluation stage started <<<<<<]
[2025-08-19 01:05:22,674:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 01:05:22,674:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 01:05:22,674:INFO:common:created directory at: artifacts]
[2025-08-19 01:05:29,484:INFO:common:json file saved at: scores.json]
[2025-08-19 01:05:29,484:INFO:common:json file saved at: scores.json]
[2025-08-19 01:05:29,484:INFO:main:>>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-08-19 01:23:42,746:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-19 01:23:42,747:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 01:23:42,747:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 01:23:42,747:INFO:common:created directory at: artifacts]
[2025-08-19 01:23:42,747:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-19 01:23:42,747:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-19 01:24:02,065:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-19 01:24:02,330:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-19 01:24:02,330:INFO:main:*******************]
[2025-08-19 01:24:02,330:INFO:main:>>>>>> stage Prepare base model started <<<<<<]
[2025-08-19 01:24:02,331:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 01:24:02,331:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 01:24:02,332:INFO:common:created directory at: artifacts]
[2025-08-19 01:24:02,332:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-19 01:24:02,488:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-19 01:24:02,515:WARNING:optimizer:At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-08-19 01:24:02,516:WARNING:__init__:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-08-19 01:24:02,536:INFO:main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-19 01:24:02,536:INFO:main:*******************]
[2025-08-19 01:24:02,536:INFO:main:>>>>>> stage Training started <<<<<<]
[2025-08-19 01:24:02,537:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 01:24:02,537:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 01:24:02,537:INFO:common:created directory at: artifacts]
[2025-08-19 01:24:02,537:INFO:common:created directory at: artifacts/training]
[2025-08-19 01:24:22,815:INFO:main:>>>>>> stage Training completed <<<<<<

x==========x]
[2025-08-19 01:24:22,815:INFO:main:*******************]
[2025-08-19 01:24:22,815:INFO:main:>>>>>> stage Evaluation stage started <<<<<<]
[2025-08-19 01:24:22,816:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 01:24:22,816:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 01:24:22,816:INFO:common:created directory at: artifacts]
[2025-08-19 01:24:29,409:INFO:common:json file saved at: scores.json]
[2025-08-19 01:24:29,409:INFO:common:json file saved at: scores.json]
[2025-08-19 01:24:30,105:ERROR:main:API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    model_evalution.main()
  File "/Users/sneha/MLOps/src/cnnClassifier/pipeline/stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "/Users/sneha/MLOps/src/cnnClassifier/components/model_evaluation_mlflow.py", line 60, in log_into_mlflow
    with mlflow.start_run():
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 418, in start_run
    active_run_obj = client.create_run(
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/tracking/client.py", line 393, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 168, in create_run
    return self.store.create_run(
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 209, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 82, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 370, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/Users/sneha/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 246, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2025-08-19 01:28:56,809:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-19 01:28:56,810:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 01:28:56,810:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 01:28:56,810:INFO:common:created directory at: artifacts]
[2025-08-19 01:28:56,810:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-19 01:28:56,810:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-19 01:29:15,141:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-19 01:29:15,402:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-19 01:29:15,402:INFO:main:*******************]
[2025-08-19 01:29:15,402:INFO:main:>>>>>> stage Prepare base model started <<<<<<]
[2025-08-19 01:29:15,403:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 01:29:15,403:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 01:29:15,403:INFO:common:created directory at: artifacts]
[2025-08-19 01:29:15,403:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-19 01:29:15,559:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-19 01:29:15,588:WARNING:optimizer:At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-08-19 01:29:15,589:WARNING:__init__:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-08-19 01:29:15,611:INFO:main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-19 01:29:15,611:INFO:main:*******************]
[2025-08-19 01:29:15,611:INFO:main:>>>>>> stage Training started <<<<<<]
[2025-08-19 01:29:15,611:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 01:29:15,612:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 01:29:15,612:INFO:common:created directory at: artifacts]
[2025-08-19 01:29:15,612:INFO:common:created directory at: artifacts/training]
[2025-08-19 01:29:35,861:INFO:main:>>>>>> stage Training completed <<<<<<

x==========x]
[2025-08-19 01:29:35,862:INFO:main:*******************]
[2025-08-19 01:29:35,862:INFO:main:>>>>>> stage Evaluation stage started <<<<<<]
[2025-08-19 01:29:35,863:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 01:29:35,863:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 01:29:35,863:INFO:common:created directory at: artifacts]
[2025-08-19 01:29:42,483:INFO:common:json file saved at: scores.json]
[2025-08-19 01:29:42,483:INFO:common:json file saved at: scores.json]
[2025-08-19 01:29:44,401:INFO:builder_impl:Assets written to: /var/folders/6h/0lk621m94411dkbcgd43t2vc0000gn/T/tmpiw6uvs19/model/data/model/assets]
[2025-08-19 01:30:16,733:INFO:main:>>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-08-19 01:32:04,283:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2025-08-19 01:32:04,283:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 01:32:04,284:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 01:32:04,284:INFO:common:created directory at: artifacts]
[2025-08-19 01:32:04,284:INFO:common:created directory at: artifacts/data_ingestion]
[2025-08-19 01:32:04,284:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-19 01:32:22,551:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1XeIX-HtiFbw47xyCqaufKl2v-CVecRZ2/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2025-08-19 01:32:22,811:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-08-19 01:32:22,811:INFO:main:*******************]
[2025-08-19 01:32:22,811:INFO:main:>>>>>> stage Prepare base model started <<<<<<]
[2025-08-19 01:32:22,812:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 01:32:22,812:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 01:32:22,812:INFO:common:created directory at: artifacts]
[2025-08-19 01:32:22,812:INFO:common:created directory at: artifacts/prepare_base_model]
[2025-08-19 01:32:22,966:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-19 01:32:22,994:WARNING:optimizer:At this time, the v2.11+ optimizer `tf.keras.optimizers.SGD` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.SGD`.]
[2025-08-19 01:32:22,995:WARNING:__init__:There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.SGD`.]
[2025-08-19 01:32:23,016:INFO:main:>>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-08-19 01:32:23,016:INFO:main:*******************]
[2025-08-19 01:32:23,016:INFO:main:>>>>>> stage Training started <<<<<<]
[2025-08-19 01:32:23,017:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 01:32:23,017:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 01:32:23,017:INFO:common:created directory at: artifacts]
[2025-08-19 01:32:23,017:INFO:common:created directory at: artifacts/training]
[2025-08-19 01:34:07,290:INFO:main:>>>>>> stage Training completed <<<<<<

x==========x]
[2025-08-19 01:34:07,290:INFO:main:*******************]
[2025-08-19 01:34:07,290:INFO:main:>>>>>> stage Evaluation stage started <<<<<<]
[2025-08-19 01:34:07,291:INFO:common:YAML file: config/config.yaml loaded successfully]
[2025-08-19 01:34:07,291:INFO:common:YAML file: params.yaml loaded successfully]
[2025-08-19 01:34:07,291:INFO:common:created directory at: artifacts]
[2025-08-19 01:34:14,199:INFO:common:json file saved at: scores.json]
[2025-08-19 01:34:14,199:INFO:common:json file saved at: scores.json]
[2025-08-19 01:34:16,103:INFO:builder_impl:Assets written to: /var/folders/6h/0lk621m94411dkbcgd43t2vc0000gn/T/tmpil79ae8i/model/data/model/assets]
[2025-08-19 01:34:50,522:INFO:main:>>>>>> stage Evaluation stage completed <<<<<<

x==========x]
